project 'AnchorSDK.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!


target 'AnchorSDK' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  #Facebook
  pod 'FBSDKCoreKit'
  #Firebase
  pod 'Firebase/Analytics'
  #AppsFlyer
  pod 'AppsFlyerFramework'
  #Umeng
   pod 'UMCCommon'
   pod 'UMCAnalytics'
  

end

